// =============================================================================
// app/layout.tsx - ROOT LAYOUT
// =============================================================================
// This is the ROOT layout for the entire Next.js application.
// It wraps ALL pages in the app and is REQUIRED in Next.js 13+ App Router.
//
// Key Responsibilities:
// 1. Defines the <html> and <body> tags (only root layout can do this)
// 2. Sets up global fonts using Next.js font optimization
// 3. Imports global CSS styles
// 4. Defines metadata for SEO (title, description)
// 5. Wraps all page content via {children}
//
// Layout Hierarchy:
// - This is the outermost layout
// - Nested layouts (like app/todos/layout.tsx) will be rendered inside {children}
// - All pages will be wrapped by this layout
//
// Important Notes:
// - This layout persists across ALL route navigations
// - It does NOT re-render when navigating between pages
// - State defined here would be shared across the entire app
// =============================================================================

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// =============================================================================
// FONT CONFIGURATION
// =============================================================================
// Next.js automatically optimizes Google Fonts:
// - Downloads fonts at build time (no runtime requests to Google)
// - Self-hosts the font files for better performance and privacy
// - Generates CSS variables for use in Tailwind/CSS

const geistSans = Geist({
  variable: "--font-geist-sans", // Creates CSS variable: var(--font-geist-sans)
  subsets: ["latin"],             // Only load Latin characters (reduces file size)
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Creates CSS variable: var(--font-geist-mono)
  subsets: ["latin"],
});

// =============================================================================
// METADATA - Used for SEO and browser tabs
// =============================================================================
// This metadata object is used by Next.js to generate:
// - <title> tag in the HTML <head>
// - <meta name="description"> tag
// - Can be overridden by page-specific metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// =============================================================================
// ROOT LAYOUT COMPONENT
// =============================================================================
// This component wraps the ENTIRE application.
// The {children} prop will be replaced with the current page content.
//
// Flow Example:
// User visits /todos → Next.js renders:
//   RootLayout (this file)
//     └─ TodosLayout (app/todos/layout.tsx)
//        └─ TodosPage (app/todos/page.tsx)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 
          {children} is where page content gets injected
          - For /todos, this would be the TodosLayout + TodosPage
          - For /, this would be the home page
          - The content changes, but this layout stays mounted
        */}
        {children}
      </body>
    </html>
  );
}
